config/routes.rb
Rails.application.routes.draw do 
  devise_for :staff_members, path: 'staff_members', controllers: {
    registrations: 'staff_members/custom_devise/registrations',
    sessions: 'staff_members/custom_devise/sessions'
  }
  
  namespace :staff_members do
    root 'products#index'

    resources :products do
      resources :prices
      resources :stocks
    end
  end

  devise_for :customers, :controllers => {
    :registrations => "custom_devise/registrations",
    :sessions => "custom_devise/sessions",
  }
    root 'products#main'

    # Product
    resources :products, only: :show

    # Search
    get '/search/products', to: 'search#products'
    
    # Carts
    put '/carts/add_product', to: 'carts#add_product'
    put '/carts/update_product', to: 'carts#update_product'
    delete '/carts/delete_product', to: 'carts#delete_product'
    get '/carts/products', to: 'carts#products'
    put  '/carts', to: 'carts#update'

    # Orders
    post  '/orders', to: 'orders#create'
    get  '/orders', to: 'orders#index'
    
    # Checkout
    get '/checkout', to: 'checkouts#view'
    put '/checkout/review', to: 'checkouts#review'

    # Credit Card
    get '/credit_cards/new', to: 'credit_cards#new'
    get '/credit_cards', to: 'credit_cards#index'
    post '/credit_cards', to: 'credit_cards#create'
    resources :credit_cards, only: [:edit, :update, :destroy]

    # Address
    get '/addresses/new', to: 'addresses#new'
    get '/addresses', to: 'addresses#index'
    post '/addresses', to: 'addresses#create'
    resources :addresses, only: [:edit, :update, :destroy]

end

app/models/price.rb
class Price < ApplicationRecord
    belongs_to :product
end

app/models/staff_member.rb
class StaffMember < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable

  belongs_to :address
  accepts_nested_attributes_for :address

  attr_accessor :first_name, :last_name

  before_create :update_name

  private

  def update_name  
    self.name = "(#{first_name},#{last_name})"
  end
end

app/controllers/staff_members/custom_devise/registrations_controller.rb
# frozen_string_literal: true
module StaffMembers
  module CustomDevise
    class RegistrationsController < Devise::RegistrationsController
      include Accessible
      skip_before_action :check_user, only: :destroy
      
      private

      def sign_up_params
          params.require(:staff_member).permit(:email, :encrypted_password, :job_title, :job_type,
              :password, :password_confirmation,:first_name, :last_name, :contact_number,
              address_attributes: [
                :first_name, :last_name, :address_line1,
                :address_line2, :zipcode, :city, :state, :phone_number
              ])
      end
    end
  end
end

app/controllers/staff_members/custom_devise/sessions_controller.rb
# frozen_string_literal: true
module StaffMembers
    module CustomDevise
        class SessionsController < Devise::SessionsController
            include Accessible
            skip_before_action :check_user, only: :destroy
        end
    end
end

app/controllers/staff_members/prices_controller.rb
module StaffMembers
    class PricesController < ApplicationController
        before_action :authenticate_staff_member!
        layout 'staff_member'

        def index
            product_id = params[:product_id]
            @product = Product.find(product_id)
            @prices = @product.prices
        end

        def new
            product_id = params[:product_id]
            @product = Product.find(product_id)
            @price = Price.new
        end

        def create
            product_id = params[:product_id]
            @product = Product.find(product_id)
            @price = @product.prices.build(create_params)
            @price.save
            if @price.errors.present?
                flash[:alert] = @price.errors.messages
                render 'staff_members/prices/new' and return
            end
            redirect_to staff_members_product_prices_path(@product.id)
        rescue StandardError => e
            flash[:alert] = e.message
            render 'staff_members/prices/new' and return
        end

        def edit
            product_id = params[:product_id]
            @product = Product.find(product_id)
            @price = @product.prices.find(params[:id])
        end


        def update
            product_id = params[:product_id]
            @product = Product.find(product_id)
            @price = @product.prices.find(params[:id])
            @price.update(create_params)
            if @price.errors.present?
                flash[:alert] = @price.errors.messages
                render 'staff_members/prices/new' and return
            end
            redirect_to staff_members_product_prices_path(@product.id)
        rescue StandardError => e
            flash[:alert] = e.message
            render 'staff_members/prices/new' and return
        end


        def destroy
            product_id = params[:product_id]
            @product = Product.find(product_id)
            @price = @product.prices.find(params[:id])
            @price.destroy
            redirect_to staff_members_product_prices_path(@product.id)
        end

        private

        def create_params
            params.require(:price).permit(:price, :state)
        end
    end
end

app/controllers/staff_members/products_controller.rb
class StaffMembers::ProductsController < ApplicationController
    before_action :authenticate_staff_member!
    layout 'staff_member'

    def index
        @products = Product.all.order('updated_at desc')
    end

    def new
        @product = Product.new
        all_categories = Category.all
        @catergory_options = category_name_and_ids(all_categories)
        @category_additional_attr = fetch_category_additional_attrs(all_categories)
    end

    def edit
        @product = Product.find(params[:id])
        all_categories = Category.all
        @catergory_options = category_name_and_ids(all_categories)
        @category_additional_attr = fetch_category_additional_attrs(all_categories)
    end

    def show
        @product = Product.find(params[:id])
    end

    def create
        all_categories = Category.all
        @catergory_options = category_name_and_ids(all_categories)
        @product = Product.new(create_params)
        @product.save
        if @product.errors.present?
            flash[:alert] = @product.errors.messages
            render 'staff_members/products/new' and return
        end
        redirect_to staff_members_products_path
    rescue StandardError => e
        flash[:alert] = e.message
        render 'staff_members/products/new'
    end

    def update
        all_categories = Category.all
        @catergory_options = category_name_and_ids(all_categories)
        @product = Product.find(params[:id])
        @product.update(create_params)
        if @product.errors.present?
            flash[:alert] = @product.errors.messages
            render 'staff_members/products/edit' and return
        end
        redirect_to staff_members_products_path
    rescue StandardError => e
        flash[:alert] = e.message
        render 'staff_members/products/edit'
    end

    def destroy
        @product = Product.find(params[:id])
        @product.destroy
        redirect_to staff_members_products_path
    end

    private


    def create_params
        params.require(:product).permit(:product_name, :product_size, :product_weight,
            :category_id, :product_description, :additional_info, :product_image)
    end

    def category_name_and_ids(all_categories)
        all_categories.collect {|c| [c.category_name, c.id]}
    end

    def fetch_category_additional_attrs(all_categories)
        category_additional_attrs = {}
        all_categories.each do|category|
            attr_hash = {}
            category.additional_info_attributes.map do|attr|
                attr_hash[attr.name] = ""
            end
            category_additional_attrs[category.id] = attr_hash
        end
        category_additional_attrs
    end
end

app/controllers/staff_members/stocks_controller.rb
class StaffMembers::StocksController < ApplicationController
    before_action :authenticate_staff_member!
    layout 'staff_member'

    def index
        product_id = params[:product_id]
        @product = Product.find(product_id)
        @stocks = @product.stocks
    end

    def new
        product_id = params[:product_id]
        @product = Product.find(product_id)
        @stock = Stock.new
        @warehouse_locations = warehouse_id_and_locations
    end

    def create
        product_id = params[:product_id]
        @product = Product.find(product_id)
        @warehouse_locations = warehouse_id_and_locations
        @stock = @product.stocks.build(create_params)
        @stock.save
        if @stock.errors.present?
            flash[:alert] = @stock.errors.messages
            render 'staff_members/stocks/new' and return
        end
        redirect_to staff_members_product_stocks_path(@product.id)
    rescue StandardError => e
        flash[:alert] = e.message
        render 'staff_members/stocks/new' and return
    end

    def edit
        product_id = params[:product_id]
        @product = Product.find(product_id)
        @warehouse_locations = warehouse_id_and_locations
        @stock = @product.stocks.find(params[:id])
    end

    def update
        product_id = params[:product_id]
        @product = Product.find(product_id)
        @warehouse_locations = warehouse_id_and_locations
        @stock = @product.stocks.find(params[:id])
        @stock.update(create_params)
        if @stock.errors.present?
            flash[:alert] = @stock.errors.messages
            render 'staff_members/stocks/new' and return
        end
        redirect_to staff_members_product_stocks_path(@product.id)
    rescue StandardError => e
        flash[:alert] = e.message
        render 'staff_members/stocks/new' and return
    end

    def destroy
        product_id = params[:product_id]
        @product = Product.find(product_id)
        @stock = @product.stocks.find(params[:id])
        @stock.destroy
        redirect_to staff_members_product_stocks_path(@product.id)
    end

    private

    def warehouse_id_and_locations
        Warehouse.all.collect {|w| [w.address.name, w.id]}
    end

    def create_params
        params.require(:stock).permit(:quantity, :warehouse_id)
    end
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/staff_members/products_helper.rb
module StaffMembers::ProductsHelper
end

app/helpers/staff_members/stocks_helper.rb
module StaffMembers::StocksHelper
end

app/views/staff_members/prices/_form.html.erb
<div>
    <div class = 'row' style = 'margin-bottom: 5px;'>
        <div class = 'col-lg-3'>
            <%= f.label(:price)%>
        </div>
        <div class = 'col-lg-9'>
            <%= f.text_field(:price, required: true)%>
        </div>
    </div>
    <div class = 'row' style = 'margin-bottom: 5px;'>
        <div class = 'col-lg-3'>
            <%= f.label(:state)%>
        </div>
        <div class = 'col-lg-9'>
            <%= f.select(:state, options_for_select(state_options)) %>
        </div>
    </div>
        <div class = 'row' style = 'margin-bottom: 5px;'>
        <div class = 'col-lg-12' style = 'text-align: center'>
            <%= f.submit('Submit', class: 'btn btn-primary')%>
            <%= link_to('Cancel', staff_members_product_prices_path(product.id), class: 'btn btn-secondary')%>
        </div>
    </div>
</div>

app/views/staff_members/prices/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h5>Edit Price</h5><br />
            <%= form_with(model: @price, url: staff_members_product_price_path(@product.id, @price.id), method: :put, local: true) do|f| %>
                <%= render 'form', f: f, state_options: AppConstants::STATES, product: @product %>
            <% end %>
        </div>
    </div>
</div>

app/views/staff_members/prices/index.html.erb
<div class="container">
    <div class = 'row'>
        <div class = 'col-lg-12 prices-form' style='text-align: right;'>
            <%= button_to('View Product', staff_members_product_path(@product.id), method: 'get', class: "btn btn-primary", style: 'display: inline;')%>&nbsp;
            <%= button_to('Add Price', new_staff_members_product_price_path(@product.id), method: 'get', class: "btn btn-primary", style: 'display: inline;')%>
            <br /><br/>
        </div>
    </div>
    <div class = 'row'>
        <div class = 'col-lg-12'>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Price</th>
                        <th scope="col">State</th>
                        <th>Actions</th>

                    </tr>
                </thead>
                <tbody>
                <% @prices.each do |price|%>
                    <tr>
                        <td scope="row">
                            <%= price.id%>
                        </td>
                        <td>
                            <%= price.price %>
                        </td>
                        <td>
                            <%= price.state %>
                        </td>
                        <td>
                            <%= link_to('Edit',  edit_staff_members_product_price_path(@product.id, price.id), method: 'get')%> &nbsp;
                            <%= link_to('Delete', staff_members_product_price_path(@product.id, price.id), method: 'delete')%>
                        </td>
                    </tr>
                <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/staff_members/prices/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h5>Add Price</h5><br />
            <%= form_with(model: @price, url: staff_members_product_prices_path, method: :post, local: true) do|f| %>
                <%= render 'form', f: f, state_options: AppConstants::STATES, product: @product %>
            <% end %>
        </div>
    </div>
</div>