config/routes.rb
Rails.application.routes.draw do 
  devise_for :staff_members, path: 'staff_members', controllers: {
    registrations: 'staff_members/custom_devise/registrations',
    sessions: 'staff_members/custom_devise/sessions'
  }
  
  namespace :staff_members do
    root 'products#index'

    resources :products do
      resources :prices
      resources :stocks
    end
  end

  devise_for :customers, :controllers => {
    :registrations => "custom_devise/registrations",
    :sessions => "custom_devise/sessions",
  }
    root 'products#main'

    # Product
    resources :products, only: :show

    # Search
    get '/search/products', to: 'search#products'
    
    # Carts
    put '/carts/add_product', to: 'carts#add_product'
    put '/carts/update_product', to: 'carts#update_product'
    delete '/carts/delete_product', to: 'carts#delete_product'
    get '/carts/products', to: 'carts#products'
    put  '/carts', to: 'carts#update'

    # Orders
    post  '/orders', to: 'orders#create'
    get  '/orders', to: 'orders#index'
    
    # Checkout
    get '/checkout', to: 'checkouts#view'
    put '/checkout/review', to: 'checkouts#review'

    # Credit Card
    get '/credit_cards/new', to: 'credit_cards#new'
    get '/credit_cards', to: 'credit_cards#index'
    post '/credit_cards', to: 'credit_cards#create'
    resources :credit_cards, only: [:edit, :update, :destroy]

    # Address
    get '/addresses/new', to: 'addresses#new'
    get '/addresses', to: 'addresses#index'
    post '/addresses', to: 'addresses#create'
    resources :addresses, only: [:edit, :update, :destroy]

end

app/models/address.rb
class Address < ApplicationRecord
    has_one :credit_card
    has_one :staff_member
    has_many :customer_addresses
    has_many :customers, through: :customer_addresses
    has_many :orders

    attr_accessor :first_name, :last_name

    before_save :update_name

    def split_name!
        names = self.name.match(/\((.*),(.*)\)/)
        self.first_name = names[1]
        self.last_name = names[2]
    end

    private

    def update_name   
        self.name = "(#{first_name},#{last_name})"
    end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
    has_many :category_additional_info_attributes
    has_many :additional_info_attributes, through: :category_additional_info_attributes
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
    has_many :orders
    
    belongs_to :customer
    belongs_to :address
    accepts_nested_attributes_for :address

    validates :card_number, uniqueness: true
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :orders
    has_many :credit_cards
    has_many :customer_addresses 
    has_many :addresses, through: :customer_addresses
    
    devise :database_authenticatable, :registerable, :validatable

    attr_accessor :first_name, :last_name

    before_create :update_name_and_status
    after_create :create_cart!

    def cart
        orders.where(status: :cart).last
    end

    def create_cart!
        return if Order.where(status: :cart, customer_id: self.id).present?
        
        Order.create!(customer_id: self.id, amount: 0.0, status: :cart, cart_shipping_state: AppConstants::STATES[0])
    end

    private

    def update_name_and_status   
        self.name = "(#{first_name},#{last_name})"
        self.status = :active
    end
end

app/models/customer_address.rb
class CustomerAddress < ApplicationRecord
    belongs_to :customer
    belongs_to :address
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_products, autosave: true
    has_many :products, through: :order_products
    
    belongs_to :customer
    belongs_to :credit_card, optional: true
    belongs_to :address, optional: true

    def create_order
        order_amount = 0
        self.status = :ordered
        self.order_number = SecureRandom.hex[0..9]
        warehouses = Warehouse.joins(:address).where(addresses: {state: self.cart_shipping_state})
        self.order_products.each do|order_product|
            order_product.price = OrderProduct.price_for_cart_shipping_state(order_product.product, self.cart_shipping_state).price
            
            product_stocks = warehouses.map{|w| w.stocks.where(product_id: order_product.product_id)[0]}.compact
            if product_stocks.map(&:quantity).sum < order_product.quantity
                self.errors.add('Quantity', "#{order_product.product.product_name} available quantity is less than ordered quantity")
                return self
            end

            remaining_quantities = order_product.quantity
            product_stocks.each do|product_stock|
                if product_stock.quantity >= remaining_quantities
                    product_stock.update!(quantity: product_stock.quantity - order_product.quantity)
                    break
                else
                    remaining_quantities = remaining_quantities - product_stock.quantity
                    product_stock.update!(quantity: 0)
                end
            end
            order_amount += order_product.price * order_product.quantity
        end
        self.amount = order_amount
        self.save
        self
    end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
    belongs_to :order
    belongs_to :product

    alias_attribute :cart, :order

    def self.price_for_cart_shipping_state(product, cart_shipping_state)
        product.prices.find{|item| item.state == cart_shipping_state}
    end
end

app/models/price.rb
class Price < ApplicationRecord
    belongs_to :product
end

app/models/product.rb
require 'carrierwave/orm/activerecord'

class Product < ApplicationRecord
    mount_uploader :product_image, ProductImageUploader

    belongs_to :category
    has_many :prices
    has_many :stocks
end

app/models/staff_member.rb
class StaffMember < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable

  belongs_to :address
  accepts_nested_attributes_for :address

  attr_accessor :first_name, :last_name

  before_create :update_name

  private

  def update_name  
    self.name = "(#{first_name},#{last_name})"
  end
end

app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :product
    belongs_to :warehouse

    validate :validate_warehouse_capacity

    private

    def validate_warehouse_capacity
        current_warehouse_stocks = Stock.where('warehouse_id = ? and product_id != ?', self.warehouse_id, self.product_id)
        current_size = current_warehouse_stocks.map {|s| s.quantity * s.product.product_size }.sum
        new_size = current_size + (self.quantity * self.product.product_size)
        if new_size > self.warehouse.storage_capacity
            self.errors.add(:quantity, "New storage size: #{new_size} exceeds warehouse storage size: #{self.warehouse.storage_capacity}")
        end
    end
end

app/models/supplier.rb
class Supplier < ApplicationRecord
end

app/models/supplier_product.rb
class SupplierProduct < ApplicationRecord
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
    belongs_to :address
    has_many :stocks
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
    before_action :authenticate_customer!, :fetch_customer_cart
    layout "checkout"

    def view
        @credit_cards = current_customer.credit_cards
        @shipping_addresses = current_customer.addresses
    end

    def review
        credit_card_id = params[:credit_card_id]
        address_id = params[:address_id]
        credit_card = current_customer.credit_cards.find(credit_card_id)
        address = current_customer.addresses.find(address_id)

        if address.state !=  @cart.cart_shipping_state
            alert_message = 'Selected shipping state is different from the cart. '
            alert_message += 'Please update the state of the cart or select a different shipping address'
            flash[:alert] = alert_message
            redirect_to checkout_path and return
        end

        @cart.update!(credit_card: credit_card, address: address)
    end

    private

    def fetch_customer_cart
        @cart = current_customer.cart
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/checkouts/review.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <%= render 'shared/checkout/products_listing', cart: @cart %>
        </div>
        <div class="col-lg-4">
            <div class="card h-100">
                <div class="card-body">
                    <h4 class="card-title">
                        <center> Summary </center>
                    </h4>
                    <%= render 'shared/checkout/products_summary', cart: @cart %>
                    <div class = 'row'>
                        <div class = 'col-lg-12'>
                            <b>Shipping to: </b>
                            <div style = 'display: flex;margin: 10px;'>
                                <%= @cart.address.name%><br/>
                                <%= @cart.address.address_line1%><br/>
                                <% if @cart.address.address_line2.present? %>
                                    <%= @cart.address.address_line2%><br/>
                                <% end %>
                                <%= @cart.address.city%><br/>
                                <%= @cart.address.zipcode%><br/>
                                <%= @cart.address.state%><br/>
                                Phone: <%= @cart.address.phone_number%><br/>
                            </div>
                        </div>
                    </div>
                    <div class = 'row'>
                        <div class = 'col-lg-12'>
                            <b>Paying with: </b>
                            <div style = 'display: flex;margin: 10px;'>
                                <%= CreditCardsHelper.mask_credit_card(@cart.credit_card.card_number)%>
                            </div>
                        </div>
                    </div>
                    <div class = 'row' style = 'margin: 40px 0px;'>
                        <div class = 'col-lg-12'>
                            <%= form_with(url: orders_path, local: true, method: 'post') do%>
                                <center> <%= submit_tag('Confirm Order') %></center>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/checkouts/view.html.erb
<div class="container">
<div class = 'row'>
    <div class = 'col-lg-8'>
        <%= form_with(url: checkout_review_path, local: true, method: 'put') do %>
            <div class="row" style="margin-bottom: 50px;">
                <div class = 'col-lg-12'>
                    <h4> Select Credit Card: </h4>
                    <% @credit_cards.each do|credit_card| %>
                        <div class = 'row'>
                            <div class = 'col-lg-12'>
                                <%= radio_button_tag('credit_card_id', credit_card.id, credit_card.id) %>
                                <%= label_tag(CreditCardsHelper.mask_credit_card(credit_card.card_number)) %>
                                <br/>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
            <div class="row">
                <div class = 'col-lg-12'>
                    <h4> Select Shipping Address: </h4>
                    <% @shipping_addresses.each do|shipping_address| %>
                        <div class = 'row'>
                            <div class = 'col-lg-12'>
                                <div style = 'float: left; margin: 10px; display: flex;'>
                                    <%= radio_button_tag('address_id', shipping_address.id, shipping_address.id) %>
                                </div>
                                <div style = 'display: flex;'>
                                    <%= shipping_address.name%><br/>
                                    <%= shipping_address.address_line1%><br/>
                                    <% if shipping_address.address_line2.present? %>
                                        <%= shipping_address.address_line2%><br/>
                                    <% end %>
                                    <%= shipping_address.city%><br/>
                                    <%= shipping_address.zipcode%><br/>
                                    <%= shipping_address.state%><br/>
                                    <%= shipping_address.phone_number%><br/>
                                </div>
                                <hr/>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
            <div class="row" style="margin-bottom: 50px;">
                <div class='col-lg-12' style = 'text-align: center'>
                    <%= submit_tag('Proceed') %>
                </div>
            </div>
        <% end %>
        </div>
        <div class = 'col-lg-4'>
            <%= form_with(url: credit_cards_new_path, local: true, method: "get" ) do%>
                <%= submit_tag('Add New Credit Card') %>
            <% end %>
            <br />
            <%= form_with(url: addresses_new_path, local: true, method: "get") do%>
                <%= submit_tag('Add New Shipping Address') %>
            <% end %>
        </div>
    </div>
</div>

app/views/shared/checkout/_products_listing.html.erb
<% cart.order_products.each do |order_product|%>
    <div class="row" style = 'border-bottom: solid 2px grey'>
        <div class="col-lg-3">
            <%= order_product.product.product_name %>
            <a href="#"><img class="card-img-top" src="<%= order_product.product.product_image.url || 'http://placehold.it/700x400'%>" alt=""></a>
        </div>
        <div class="col-lg-9">               
            <div class = 'row' style='padding: 10px;'>
                <div class = 'col-lg-3'>
                    <b>Price:</b>
                </div>
                <div class= 'col-lg-9'>
                        $<%= OrderProduct.price_for_cart_shipping_state(order_product.product, cart.cart_shipping_state).price %>
                </div>
            </div>
                <%= form_with(url: carts_update_product_path, local: true, method: 'put') do%>
                    <%= hidden_field_tag(:product_id, order_product.product.id) %>
                    <div class = 'row' style='padding: 10px;'>
                    <div class = 'col-lg-3'>
                        <b>Quantity:</b>
                    </div>
                    <div class = 'col-lg-9'>
                        <%= number_field_tag(:quantity, order_product.quantity, min: 1, style: "width: 40px") %>
                        <%= submit_tag('Update') %>
                    </div>
                    </div>
                <% end %>
            <div class = 'row' style='padding: 10px;'>
                <div class = 'col-lg-3'></div>
                <div class = 'col-lg-9'>
                    <%= form_with(url: carts_delete_product_path, local: true, method: 'delete') do %>
                        <%= hidden_field_tag(:product_id, order_product.product.id) %>
                        <%= submit_tag('Delete') %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/shared/checkout/_products_summary.html.erb
<p class="card-text">
    <% total = 0 %>
    <% cart.order_products.each do |order_product|%>
        <div class = 'row'>
            <div class = 'col-lg-9'>
                <%= order_product.product.product_name%>:
            </div>
            <div class = 'col-lg-3'>
                <% price = OrderProduct.price_for_cart_shipping_state(order_product.product, cart.cart_shipping_state).price %>
                <% total +=  order_product.quantity * price %>
                $<%= order_product.quantity * price %>
            </div>
        </div>
    <% end %>
</p>
<div class = 'row'>
    <div class = 'col-lg-9'>
        <b>Total:</b>
    </div>
    <div class = 'col-lg-3'>
        $<%= total %>
    </div>
</div>